Back Propogation Using Pytorch
y=x^2

In [1]:
import torch

In [2]:
x = torch.tensor(4.0,requires_grad=True)

In [3]:
x

tensor(4., requires_grad=True)

In [4]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [6]:
y.backward()

In [8]:
x.grad

tensor(8.)

In [10]:
lst = [[2.,5.,9.],[6.,4.,3.],[1.,10.,3.]]
torch_input = torch.tensor(lst, requires_grad=True)

In [11]:
torch_input

tensor([[ 2.,  5.,  9.],
        [ 6.,  4.,  3.],
        [ 1., 10.,  3.]], requires_grad=True)

In [17]:
### y=x**3+x**2
### y=3x**2+2x--->
y = torch_input**3 + torch_input**2

In [18]:
y

tensor([[  12.,  150.,  810.],
        [ 252.,   80.,   36.],
        [   2., 1100.,   36.]], grad_fn=<AddBackward0>)

In [20]:
z = y.sum()

In [21]:
z

tensor(2478., grad_fn=<SumBackward0>)

In [22]:
z.backward()

In [24]:
torch_input.grad

tensor([[ 16.,  85., 261.],
        [120.,  56.,  33.],
        [  5., 320.,  33.]])