In [1]:
import torch

In [2]:
import numpy as np


In [4]:
lst = [3,6,8,1,4]
arr = np.array(lst)
arr

array([3, 6, 8, 1, 4])

In [5]:
arr.dtype

dtype('int64')

Convert Numpy To Pytorch Tensors

In [6]:
tensors = torch.from_numpy(arr)

In [7]:
tensors

tensor([3, 6, 8, 1, 4])

In [8]:
tensors.dtype

torch.int64

In [9]:
### Indexing similar to numpy
tensors[2]

tensor(8)

In [11]:
tensors[1:]

tensor([6, 8, 1, 4])

In [12]:
#### Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [13]:
tensors

tensor([  3,   6,   8, 100,   4])

In [14]:
arr

array([  3,   6,   8, 100,   4])

In [15]:
### Prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)

In [16]:
tensor_arr

tensor([  3,   6,   8, 100,   4])

In [17]:
tensor_arr[3]= 120
print(tensor_arr)
print(arr)

tensor([  3,   6,   8, 120,   4])
[  3   6   8 100   4]


In [18]:
##zeros and ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Arithmetic Operation

In [23]:
a = torch.tensor([2,3,4],dtype=torch.float)
b = torch.tensor([6,7,8],dtype=float)


In [24]:
a+b

tensor([ 8., 10., 12.], dtype=torch.float64)

In [25]:
torch.add(a,b)

tensor([ 8., 10., 12.], dtype=torch.float64)

In [28]:
c=torch.zeros(3)

In [29]:
torch.add(a,b,out=c)

tensor([ 8., 10., 12.])

In [30]:
c

tensor([ 8., 10., 12.])

In [31]:
torch.add(a,b).sum()

tensor(30., dtype=torch.float64)

Dot Products and Mult Operations

In [32]:
x = torch.tensor([4,5,6], dtype=torch.float)
y = torch.tensor([9,1,2], dtype=torch.float)


In [33]:
x.mul(y)

tensor([36.,  5., 12.])

In [ ]:
##4*9,5*1,6*2

In [34]:
x.dot(y)

tensor(53.)

In [35]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [38]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [39]:
x@y

tensor([[55., 53.],
        [90., 92.]])

In [40]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])